
name: Test
on: workflow_dispatch

jobs:
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      security-events: write
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/normalenterprise/wiz_test

      - name: "Build Docker image release candidate"
        uses: docker/build-push-action@v6
        id: rc_image
        with:
          context: ./
          push: true
          load: true
          tags: ghcr.io/normalenterprise/wiz_test:rc

      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Authenticate to Wiz
        run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Run wiz-cli docker image scan
        id: run-cli
        run: |
          output=$(./wizcli docker scan --image ghcr.io/normalenterprise/wiz_test:rc --policy "jannasch - vcs - vuln" --tag github_action_run_id=${{ github.run_id }} --output output_scan.sarif,sarif)
          echo "::set-output name=cli_output::$output"

      # - name: Fetch digest of Docker image for Graph enrichment
      #   run: |
      #     echo "Digest before push: ${{ steps.rc_image.outputs.digest }}"
      #     echo "Tag WizCLI"
      #     ./wizcli docker tag --image ghcr.io/normalenterprise/wiz_test:rc --digest ${{ steps.rc_image.outputs.digest }}
      #     echo "Tag WizCLI 2"
      #     ./wizcli docker tag --image ghcr.io/normalenterprise/wiz_test:rc

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "$RUNNER_OUTPUT"
        env:
          RUNNER_OUTPUT: ${{ steps.run-cli.outputs.cli_output }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        continue-on-error: true
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: output_scan.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: wiz